### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by NelsonAraujo93** [MMGGYY66/leaderboard#4]
Greetings @MMGGYY66 , your project looks amazing and it works perfectly. We checked your code and want to give you some feedback about it.

**Highlights:**
- Your User Interface looks amazing, nice using of Bootstrap. 👍🏽 
- The API are consumed with async and await in proper way. 👍🏽 
- Nice use and configuration of web-pack. 👍🏽 
- Clean and Dry code.

**Suggestions:**
- It would be nice to add an scroll-y in the score list to avoid the ui get to much height. 💯 
- You can also add more HTML5 semantic tags such as ( section, article ) to enhance HTML5 best practices. 💯

**Comment by MMGGYY66** [comment]
thank a lot all of you
