### ISSUE TITLE
Morning Session Feb 7 2023

### ISSUE THREAD

**Issue by kensteph** [MMGGYY66/leaderboard#5]
Hi @MMGGYY66 ! You did a great job!  👍 

### HIGHLIGHTS
- Clean code 👍 
- HTML best practices 👍 

### SUGGESTIONS
@kensteph
- I think it would be better to add the scrollbar for the score list only. This will improve the user experience.
- I can see in line 81 in your template file (index.htm) you link the index.j file. I think it is not necessary as you use webpack. Webpack will manage it for you.
`<script src="./src/index.js" type="text/javascript"></script>`
- It would be better to use arrow function here on line 31 instead of traditional  as it is a requirement for the project
`function loadGithubIcon() {
  const github = document.getElementById('github');
  github.src = Github;
  github.alt = 'github';
  github.setAttribute('class', 'github-icon');
}`

@edahigure
The program is very good. It was a good idea to create a class for the leaderboard and implement there the post and get methods. Also the styling is very good. Also it creates the id of the game automatically. The only possible issue is that when one reload the page the scores will disappear. Could it be possible to save the id of a game to reload the game again or not?

@miltonHenschel
- Great design
- Use of modules
- Use of arrow functions
- Use of semantic tags
- Use of Gitflow
- Use of GitHub flow
- Use of async/await

**Comment by MMGGYY66** [comment]
thank you all
